### ISSUE TITLE
Overwriting/extending existing sharing settings

### ISSUE THREAD

**Issue by faraimuterohisp** [davidhuser/dhis2-pocket-knife#10]
Hi David. 

Please see the following issue from one of our Lead Data Managers:

Farai

We were given the following script to use when changing sharing settings. 

dhis2-pk-share -s https://staging.dhis.dhmis.org/fs_591606 -u ##### -p ##### -t dataelement -f name:ilike:antenatal -a readwrite -g "name:like:Facilitator" readwrite -g "name:like:Dashboard Managers" none

In the example above the script will change any data element with the word “antenatal to  “Public Access” readwrite and it will change the selected groups “Facilitator” & “Dashboard Managers” to readwrite and none respectively. The problem we have is that if there where any other groups already in the sharing settings that we do not want to amend it will now be removed from the selection above as it is not part of the script. What we need the script to do is ignore current groups where no amendment is made and leave it in the sharing settings.

Hope it is clear

Thanks

Kind Regards

Hans Naude

Team Coordinator: Data Management

**Comment by davidhuser** [comment]
Hi, this is a slightly larger development as the API to actually share an object is not similar to the one to read an existing one. So for now you would need to re-specify. I don't have time to do that immediately but I'm happy to review Pull Requests.

**Comment by olavpo** [comment]
Hi, just adding my vote for this! (I actually misunderstood the -o flag initially, thinking "overwrite" referred to whether to keep existing sharing settings or not).

**Comment by davidhuser** [comment]
Thanks for letting me know @faraimuterohisp and @olavpo.
I have a draft version ready in the development branch. https://github.com/davidhuser/dhis2-pk/blob/development/docs/share.md#example-3-extending-existing-sharing-settings

A few further explanations

- it would use the flag `-e` for _extend_ (no further argument required)
- when a user group is already defined on the object you want to extend the sharing, the **supplied** sharing setting for that user group takes precedence (i.e. what you type into the terminal overwrites what is on the server for that same user group).
- public access argument `-a` can be omitted, if that is done it will re-use / inherit the `publicAccess` settings already present, otherwise it will apply what is provided.
- _unrelated but important_: next release already has the feature to omit the `-p` password argument for security. You can type / paste it afterwards. This way passwords won't be stored in the terminal history and it's easier to share full commands.

Please let me know if you like that or not or if there is anything I forgot, and if you would like to test it before the wider release.

**Comment by davidhuser** [comment]
This has now been implemented in release 0.32.3 https://github.com/davidhuser/dhis2-pk/releases/tag/v0.32.3
